from typing import Optional

from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    "A query request to the llm"

    question: str = Field(
        min_length=3,
        max_length=1000,
        description="User question",
        examples=["What is Machine Learning ?"],
    )

    top_k: Optional[int] = Field(
        default=None,
        ge=1,  # ge = "greater or equal" → minimum of 1
        le=20,  # le = "less or equal" → maximum of 20
        description="How many documents to retrieve (overrides the default)",
    )


class SourceDocument(BaseModel):
    "A source document returned with response -> Shows where the information was found from"

    id: str
    content: str  # fragment of the document
    source: str  # name/path of original file
    score: float  # similarity score (0 to 1)
    # The higher the score, the more relevant the chunk was
    # for the question.


class QueryResponse(BaseModel):
    "What the api returns to the user"

    answer: str  # answer generated by the llm
    sources: list[SourceDocument]  # used documents
    question: str
    # is usefull returning answers for debugging


class IngestRequest(BaseModel):
    "Request body for text ingestion"

    text: str = Field(min_length=10)
    source_name: str = Field(description="Document ID", example="product-manual-v2")


class IngestResponse(BaseModel):
    "Response after ingestion"

    message: str
    chunks_created: int  # how much chunks was indexed
    source: str
