from typing import Optional
from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    "A query request to the llm"

    question: str = Field(
        min_length=3,
        max_length=1000,
        description="User question",
        examples=["What is Machine Learning ?"],
    )

    top_k: Optional[int] = Field(
        default=None,
        ge=1,  # ge = "greater or equal" → minimum of 1
        le=20,  # le = "less or equal" → maximum of 20
        description="How many documents to retrieve (overrides the default)",
    )


class SourceDocument(BaseModel):
    "A source document returned with response -> Shows where the information was found"

    id: str
    content: str  # fragment of the document
    source: str  # name/path of original file
    score: float  # similarity score (0 to 1)
    # The higher the score, the more relevant the chunk was
    # for the question.


class QueryResponse(BaseModel):
    "What the api returns to the user"

    answer: str  # answer generated by the llm
    sources: list[SourceDocument]  # used documents
    question: str # is usefull returning answers for debugging


class IngestRequest(BaseModel):
    "Request body for text ingestion"

    text: str = Field(min_length=10)
    source_name: str = Field(description="Document ID", example="product-manual-v2")


class IngestResponse(BaseModel):
    "Response after ingestion"

    message: str
    chunks_created: int  # how much chunks was indexed
    source: str


# ── Retrieval Observability ──────────────────────────────────────────────

class RetrievalExplainRequest(BaseModel):
    query: str = Field(min_length=1, max_length=1000)
    top_k: Optional[int] = Field(
        default=None, ge=1, le=50,
        description="How many documents to retrieve per stage",
    )


class BM25ResultItem(BaseModel):
    rank: int
    score: float
    document_id: str
    source_name: str
    text_preview: str


class VectorResultItem(BaseModel):
    rank: int
    score: float
    document_id: str
    source_name: str
    text_preview: str


class HybridResultItem(BaseModel):
    rank: int
    rrf_score: float
    document_id: str
    source_name: str
    bm25_rank: Optional[int] = None
    bm25_score: Optional[float] = None
    vector_rank: Optional[int] = None
    vector_score: Optional[float] = None


class RerankedResultItem(BaseModel):
    rank: int
    reranker_score: float
    document_id: str
    source_name: str
    previous_hybrid_rank: int


class RetrievalExplainResponse(BaseModel):
    query: str
    bm25_results: list[BM25ResultItem]
    vector_results: list[VectorResultItem]
    hybrid_results: list[HybridResultItem]
    reranked_results: list[RerankedResultItem]
